### ISSUE TITLE
Should links be non-nullable in HalRepresentation?

### ISSUE THREAD

**Issue by jasonmitchell** [jasonmitchell/hallo#12]
In general it wouldn't be expected for a consumer to implement `LinksFor` and return `null` however the default behaviour when `LinksFor` is not implemented is to return null.  Perhaps this should return an empty collection?

Requires #11 to be resolved before links can be non-nullable.

**Comment by j0nnyhughes** [comment]
Spec says:

> Each Resource Object SHOULD contain a 'self' link that corresponds with the IANA registered 'self' relation (as defined by [RFC5988]) whose target is the resource's URI.

Either LinksFor is required to provide the `self` link or is it possible to generate `self` and use LinksFor for additional links?
