### ISSUE TITLE
Thoughts on having 2 packages, 1 for MVC, 1 for ASP.NET Core

### ISSUE THREAD

**Issue by jchannon** [jasonmitchell/hallo#51]
The ouputformatter is actually the MVC specific part here but we could move that logic into a class which an outputformatter calls and we could publish a package just for MVC.  That logic can then be used inside a ASP.NET Core package where we could provide extensions similar to 

`Use((next,ctx) => halHandler(next,ctx))`

`halHandler` would also then call the class with the logic in it and write to the response stream directly

That way C# and F# devs could use the lib

What do you think?

**Comment by jasonmitchell** [comment]
This is a pretty good idea. I wonder is it worth taking this even further and moving some core classes like `HalRepresentation` out into a separate package to allow the flexibility for consumers to define representations in projects without a reference to ASP.NET.

**Comment by jchannon** [comment]
Cunning! I like it
